### ISSUE TITLE
Project Framework Version

### ISSUE THREAD

**Issue by Shorotshishir** [harmeg1ddo/project_undefined#1]
I see the `.gitignore` file added in repository is for unity. I am assuming this will be a Unity Project. In that case, do we have any particular version of Unity in mind ?

I saw unity released their latest `LTS 2022.3.0f1` [Link to LTS Page](https://unity.com/releases/editor/qa/lts-releases)

what about this one ?

**Comment by harmeg1ddo** [comment]
I did not have any particular version in mind however you put forward a good suggestion. I think we shouldd go with that version and see if we can incorporate any new feature in this practice project.

**Comment by Shorotshishir** [comment]
Ok, then share the basic unity project created in `Unity 2022.3.0 LTS`, so that we can clone it and start working on it.

**Comment by harmeg1ddo** [comment]
I added a basic unity project to the main branch. I used the 2022.3.1f as the version since that is the latest one.

**Comment by Shorotshishir** [comment]
Thank you. I cloned the project and could open it with 2022.3.1 .
I will close the issue as we could decide which project version to use
