### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by Shorotshishir** [harmeg1ddo/project_undefined#3]
I think it is high time we come up with a generic project structure. I am thinking about a specific structure, and I will be using a tool that I created a While back 

https://github.com/Shorotshishir/EditorTools/tree/main 

Using this tool I will create the full folder structure of the project. 
this will be the basic structure
```
_Project\
_Project\Materials\
_Project\Media\Audio
_Project\Media\Images
_Project\Media\Video
_Project\Prefabs\
_Project\Scenes\
_Project\Scripts\
```

I think this will be a better structure of the project

**Comment by harmeg1ddo** [comment]
That looks great! Thank you for the initialization
